import Foundation

enum AppGroupConstants {
    static let suiteName = "group.com.polamgh.ali.AzadiTunnel"
    static let psiphonConfigKey = "psiphon_config_json"
    static let psiphonConfigBaseKey = "psiphon_config_base_json"
    static let psiphonServerEntriesKey = "psiphon_server_entries"
    static let psiphonServerEntriesLineCountKey = "psiphon_server_entries_line_count"
    static let psiphonServerEntriesFileName = "psiphon-embedded-server-entries.txt"
    static let psiphonBootstrapInstalledKey = "psiphon_bootstrap_installed"
    static let psiphonBootstrapVersionKey = "psiphon_bootstrap_app_version"
    static let psiphonUsesBundledConfigKey = "psiphon_uses_bundled_config"
    static let appSettingsKey = "app_settings_json"
    static let sharedLogsKey = "shared_logs"
    static let vpnStatusKey = "vpn_status"
    static let testModeKey = "ui_test_mode"
    static let lastInternetTestOKKey = "last_internet_test_ok"
    static let psiphonTunnelEstablishedKey = "psiphon_tunnel_established"

    /// Persisted runtime state for the LAN proxy bridge (written by extension, read by UI).
    static let lanProxyStatusKey = "lan_proxy_status"
    static let lanProxyBoundHostKey = "lan_proxy_bound_host"
    static let lanProxyActiveHttpPortKey = "lan_proxy_active_http_port"
    static let lanProxyActiveSocksPortKey = "lan_proxy_active_socks_port"
    static let lanProxyStatusDetailKey = "lan_proxy_status_detail"

    /// Iran-bypass: cached CIDR list (file, one entry per line) + metadata.
    static let bypassIranCidrFileName = "bypass-iran-cidr.txt"
    static let bypassIranListUpdatedKey = "bypass_iran_list_updated_at"
    static let bypassIranListCountKey = "bypass_iran_list_count"
    /// Cached domain → resolved IPv4 list (JSON file) for domain-based bypass.
    static let bypassDomainIPsFileName = "bypass-domain-ips.json"
    static let bypassDomainsUpdatedKey = "bypass_domains_updated_at"
    /// Route count the extension actually applied to `excludedRoutes` (published for UI).
    static let bypassRoutesAppliedCountKey = "bypass_routes_applied_count"
}

enum SharedLogEvent: String, CaseIterable {
    case appBoot = "APP_BOOT"
    case vpnConnectRequested = "VPN_CONNECT_REQUESTED"
    case vpnDisconnectRequested = "VPN_DISCONNECT_REQUESTED"
    case vpnStatusChanged = "VPN_STATUS_CHANGED"
    case extensionBoot = "EXTENSION_BOOT"
    case extensionStartEntered = "EXTENSION_START_ENTERED"
    case extensionStopEntered = "EXTENSION_STOP_ENTERED"
    case extensionSettingsLoaded = "EXTENSION_SETTINGS_LOADED"
    case vpnManagerCreated = "VPN_MANAGER_CREATED"
    case vpnManagerReused = "VPN_MANAGER_REUSED"
    case vpnManagerSaved = "VPN_MANAGER_SAVED"
    case vpnStartRequested = "VPN_START_REQUESTED"
    case vpnStopRequested = "VPN_STOP_REQUESTED"
    case configImportOpened = "CONFIG_IMPORT_OPENED"
    case configValidateOK = "CONFIG_VALIDATE_OK"
    case configValidateFailed = "CONFIG_VALIDATE_FAILED"
    case configSaved = "CONFIG_SAVED"
    case psiphonConfigFound = "PSIPHON_CONFIG_FOUND"
    case psiphonConfigInstalled = "PSIPHON_CONFIG_INSTALLED"
    case psiphonBundledConfigFound = "PSIPHON_BUNDLED_CONFIG_FOUND"
    case psiphonBundledConfigInstallFailed = "PSIPHON_BUNDLED_CONFIG_INSTALL_FAILED"
    case psiphonBundledConfigInstalled = "PSIPHON_BUNDLED_CONFIG_INSTALLED"
    case psiphonServerEntriesLoaded = "PSIPHON_SERVER_ENTRIES_LOADED"
    case psiphonConnectUsingBundledConfig = "PSIPHON_CONNECT_USING_BUNDLED_CONFIG"
    case psiphonCoreSelected = "PSIPHON_CORE_SELECTED"
    case psiphonConfigValid = "PSIPHON_CONFIG_VALID"
    case psiphonConnectRequested = "PSIPHON_CONNECT_REQUESTED"
    case psiphonConnected = "PSIPHON_CONNECTED"
    case psiphonDisconnected = "PSIPHON_DISCONNECTED"
    case psiphonConnectFailed = "PSIPHON_CONNECT_FAILED"
    case psiphonStartRequested = "PSIPHON_START_REQUESTED"
    case psiphonStarted = "PSIPHON_STARTED"
    case psiphonLocalProxy = "PSIPHON_LOCAL_PROXY"
    case psiphonStartFailed = "PSIPHON_START_FAILED"
    case psiphonStopRequested = "PSIPHON_STOP_REQUESTED"
    case psiphonStopped = "PSIPHON_STOPPED"
    case coreSelected = "CORE_SELECTED"
    case psiphonProxyReady = "PSIPHON_PROXY_READY"
    case psiphonTunnelEstablished = "PSIPHON_TUNNEL_ESTABLISHED"
    case packetForwardingStartRequested = "PACKET_FORWARDING_START_REQUESTED"
    case packetForwardingStarted = "PACKET_FORWARDING_STARTED"
    case tunnelConnected = "TUNNEL_CONNECTED"
    case tunnelStartFailed = "TUNNEL_START_FAILED"
    case tunnelStopCleanup = "TUNNEL_STOP_CLEANUP"
    case settingChanged = "SETTING_CHANGED"
    case settingsResetToDefaults = "SETTINGS_RESET_TO_DEFAULTS"
    case internetTestPassed = "INTERNET_TEST_PASSED"
    case internetTestFailed = "INTERNET_TEST_FAILED"
    case dnsForwardOk = "DNS_FORWARD_OK"
    case dnsForwardFailed = "DNS_FORWARD_FAILED"
    case tcpRelayOk = "TCP_RELAY_OK"
    case lanProxySettingOpened = "LAN_PROXY_SETTING_OPENED"
    case lanProxyEnabled = "LAN_PROXY_ENABLED"
    case lanProxyDisabled = "LAN_PROXY_DISABLED"
    case lanProxyWifiDetected = "LAN_PROXY_WIFI_IP_DETECTED"
    case lanProxyWifiMissing = "LAN_PROXY_WIFI_IP_MISSING"
    case lanProxyHttpListening = "LAN_PROXY_HTTP_LISTENING"
    case lanProxySocksListening = "LAN_PROXY_SOCKS_LISTENING"
    case lanProxyHttpStopped = "LAN_PROXY_HTTP_STOPPED"
    case lanProxySocksStopped = "LAN_PROXY_SOCKS_STOPPED"
    case lanProxyHttpBindFailed = "LAN_PROXY_HTTP_BIND_FAILED"
    case lanProxySocksBindFailed = "LAN_PROXY_SOCKS_BIND_FAILED"
    case lanProxyPortInUse = "LAN_PROXY_PORT_IN_USE"
    case lanProxyVpnDisconnected = "LAN_PROXY_VPN_DISCONNECTED_STOP"
    case lanProxyVpnReconnected = "LAN_PROXY_VPN_RECONNECTED_RESTART"
    case lanProxyAuthEnabled = "LAN_PROXY_AUTH_ENABLED"
    case lanProxyAuthDisabled = "LAN_PROXY_AUTH_DISABLED"
    case lanProxyPortsChanged = "LAN_PROXY_PORTS_CHANGED"
    case lanProxyAcceptError = "LAN_PROXY_ACCEPT_ERROR"
    case lanProxyForwardError = "LAN_PROXY_FORWARD_ERROR"
    case lanProxyHttpClientConnected = "LAN_PROXY_HTTP_CLIENT_CONNECTED"
    case lanProxyHttpRequestLine = "LAN_PROXY_HTTP_REQUEST_LINE"
    case lanProxyHttpConnectHost = "LAN_PROXY_HTTP_CONNECT_HOST"
    case lanProxyHttpConnectEstablished = "LAN_PROXY_HTTP_CONNECT_ESTABLISHED"
    case lanProxyHttpConnectFailed = "LAN_PROXY_HTTP_CONNECT_FAILED"
    case lanProxySocksClientConnected = "LAN_PROXY_SOCKS_CLIENT_CONNECTED"
    case lanProxySocksGreetingReceived = "LAN_PROXY_SOCKS_GREETING_RECEIVED"
    case lanProxySocksConnectHost = "LAN_PROXY_SOCKS_CONNECT_HOST"
    case lanProxySocksConnectEstablished = "LAN_PROXY_SOCKS_CONNECT_ESTABLISHED"
    case lanProxyRelayStarted = "LAN_PROXY_RELAY_STARTED"
    case lanProxyRelayClosed = "LAN_PROXY_RELAY_CLOSED"
    case lanProxyRelayError = "LAN_PROXY_RELAY_ERROR"
    case proxyOnlyModeEnabled = "PROXY_ONLY_MODE_ENABLED"
    case proxyOnlyModeDisabled = "PROXY_ONLY_MODE_DISABLED"
    case proxyOnlyHttpListening = "PROXY_ONLY_HTTP_LISTENING"
    case proxyOnlySocksListening = "PROXY_ONLY_SOCKS_LISTENING"
    case proxyOnlyNoDefaultRoute = "PROXY_ONLY_NO_DEFAULT_ROUTE"
    case proxyOnlyNoSystemProxy = "PROXY_ONLY_NO_SYSTEM_PROXY"
    case proxyOnlyClientConnected = "PROXY_ONLY_CLIENT_CONNECTED"
    case proxyOnlyWarningNotFullVPN = "PROXY_ONLY_WARNING_NOT_FULL_VPN"
    case proxyOnlySocksClientConnected = "PROXY_ONLY_SOCKS_CLIENT_CONNECTED"
    case proxyOnlySocksHandshakeOk = "PROXY_ONLY_SOCKS_HANDSHAKE_OK"
    case proxyOnlySocksHandshakeFailed = "PROXY_ONLY_SOCKS_HANDSHAKE_FAILED"
    case proxyOnlySocksSelfTestLoopback = "PROXY_ONLY_SOCKS_SELF_TEST_LOOPBACK"
    case proxyOnlySocksSelfTestWifi = "PROXY_ONLY_SOCKS_SELF_TEST_WIFI"
    case proxyOnlySocksSelfTestExtension = "PROXY_ONLY_SOCKS_SELF_TEST_EXTENSION"
    case proxyOnlyBlockedNoWifi = "PROXY_ONLY_BLOCKED_NO_WIFI"
    case proxyOnlyDisableOffered = "PROXY_ONLY_DISABLE_OFFERED"
    case proxyOnlyDisabledByUser = "PROXY_ONLY_DISABLED_BY_USER"
    case proxyOnlyStartCancelledNoWifi = "PROXY_ONLY_START_CANCELLED_NO_WIFI"
    case bypassIranEnabled = "BYPASS_IRAN_ENABLED"
    case bypassIranDisabled = "BYPASS_IRAN_DISABLED"
    case bypassIranListFetchStarted = "BYPASS_IRAN_LIST_FETCH_STARTED"
    case bypassIranListFetchOk = "BYPASS_IRAN_LIST_FETCH_OK"
    case bypassIranListFetchFailed = "BYPASS_IRAN_LIST_FETCH_FAILED"
    case bypassIranListCacheUsed = "BYPASS_IRAN_LIST_CACHE_USED"
    case bypassIranNoListWarning = "BYPASS_IRAN_NO_LIST_WARNING"
    case bypassIranRoutesApplied = "BYPASS_IRAN_ROUTES_APPLIED"
    case bypassCustomRouteAdded = "BYPASS_CUSTOM_ROUTE_ADDED"
    case bypassDomainResolved = "BYPASS_DOMAIN_RESOLVED"
    case bypassDomainFailed = "BYPASS_DOMAIN_FAILED"
    case bypassProxyDisabledForRoutes = "BYPASS_PROXY_DISABLED_FOR_ROUTES"
}

enum VPNStatusDisplay: String, Codable {
    case disconnected
    case connecting
    case connected
    case disconnecting
    case error
}

/// Runtime state of the LAN proxy bridge published by the extension for UI consumption.
enum LANProxyRuntimeStatus: String, Codable {
    case stopped
    case running
    case vpnDisconnected = "vpn_disconnected"
    case noWifiIP = "no_wifi_ip"
    case portInUse = "port_in_use"
    case failedToStart = "failed_to_start"
}
