import Foundation

enum AppLocalizationUI {
    static func register() {
        AppLanguageController.registerExtraTranslations(en: en, fa: fa)
    }

    private static let en: [AppLanguageController.L10nKey: String] = [
        .supportButton: "Support",
        .splashTagline: "Privacy-focused tunnel for a more open internet",
        .diagnosticsSection: "Connection diagnostics",
        .vpnPing: "Ping",
        .refreshPing: "Refresh ping",
        .copy: "Copy",
        .copiedToClipboard: "Copied to clipboard",
        .testPass: "PASS",
        .testFail: "FAIL",
        .configSetupBanner: "Bundled Psiphon config is missing or invalid. Use Settings → Advanced → Retry bundled install.",
        .onboardingNavTitle: "Welcome",
        .onboardingWelcomeTitle: "Welcome to AzadiTunnel",
        .onboardingWelcomeBody: "AzadiTunnel routes your device traffic through an encrypted Psiphon tunnel so apps can reach the open internet more reliably.",
        .onboardingPrivacyTitle: "Privacy first",
        .onboardingPrivacyBody: "Diagnostics stay on your device. Export debug reports only when you choose. We do not sell your traffic data.",
        .onboardingTransportTitle: "Transport modes",
        .onboardingTransportBody: "Choose Auto, Direct, CDN fronting, or Conduit in Settings. Beast mode speeds up tunnel establishment when enabled.",
        .onboardingFallbackTitle: "Smart fallback",
        .onboardingFallbackBody: "If CDN fronting fails, the app can try Auto+Beast and then Direct automatically, with clear logs for each step.",
        .onboardingSupportTitle: "Support development",
        .onboardingSupportBody: "VPN features stay free. Optional tips and subscriptions help improve the app—open Support from the home screen.",
        .onboardingContinue: "Continue",
        .onboardingGetStarted: "Get started",
        .onboardingSkip: "Skip",
        .protocolAuto: "Auto",
        .protocolDirect: "Direct",
        .protocolCDN: "CDN fronting",
        .protocolConduit: "Conduit",
        .conduitModeAuto: "Auto (community then public)",
        .conduitModeCommunity: "Community",
        .conduitModePublic: "Public",
        .settingsConnection: "Connection",
        .settingsConfigSource: "Config source",
        .settingsBundled: "Bundled",
        .settingsCustom: "Custom",
        .settingsServerEntries: "Embedded server entries",
        .settingsRegion: "Region",
        .settingsEgressRegion: "Egress region",
        .settingsRegionHint: "Region applies on the next connect.",
        .settingsTransport: "Transport",
        .settingsProtocol: "Protocol",
        .settingsBeastMode: "Beast mode",
        .settingsConduitMode: "Conduit mode",
        .settingsBlockCensored: "Block censored-country relays",
        .settingsConduitTimeout: "Auto fallback timeout",
        .settingsCDNFronting: "CDN fronting",
        .settingsCDNExpert: "Expert overrides for CDN edge IPs, SNI, and scan.",
        .settingsCDNBuiltinScan: "Built-in CDN scan",
        .settingsCDNEdgeIPs: "CDN edge IPs",
        .settingsCDNSNI: "CDN SNI hostnames",
        .settingsCDNEdgesSummary: "Built-in edges",
        .settingsProxy: "Upstream proxy",
        .settingsProxyEnable: "Enable upstream proxy",
        .settingsProxyHost: "Host",
        .settingsProxyPort: "Port",
        .settingsProxySystem: "Use system proxy",
        .settingsBehavior: "Behavior",
        .settingsSmartFallback: "Smart fallback (CDN → Auto+Beast → Direct)",
        .settingsAutoRetryNoInternet: "Smart recovery (no internet)",
        .settingsAutoRetryNoInternetHelp: "If the tunnel connects but sites do not load, automatically tries saved best route, CDN/Auto/Direct, egress regions, Beast, messaging compat, and Conduit fallbacks.",
        .settingsAutoReconnect: "Auto-reconnect",
        .settingsConnectOnLaunch: "Connect on launch",
        .settingsVPNOnDemand: "VPN On Demand",
        .settingsVPNOnDemandMode: "Connect when",
        .settingsVPNOnDemandHelp: "iOS connects the tunnel automatically when the rule matches. Install the VPN profile once by tapping Connect on Home.",
        .onDemandAlways: "Any network",
        .onDemandWiFi: "Wi‑Fi only",
        .onDemandCellular: "Cellular only",
        .settingsAdvanced: "Advanced / Developer",
        .settingsAdvancedHint: "Tap Connect on Home to start. Import is optional.",
        .settingsRetryBundled: "Retry bundled install",
        .settingsRetryBundledFailed: "Bundled install failed — see Logs.",
        .settingsResetDefaults: "Reset settings to defaults",
        .settingsResetDefaultsConfirmTitle: "Reset settings?",
        .settingsResetDefaultsConfirmMessage: "This restores all connection and behavior settings to their defaults. Your language choice and legal acceptance will be kept. Psiphon config import is not changed.",
        .settingsResetDefaultsDone: "Settings reset to defaults",
        .settingsBundledInstallSuccess: "Bundled config installed successfully.",
        .settingsConfigImportSuccess: "Custom config imported successfully.",
        .settingsConfigImportFailed: "Config import failed.",
        .settingsDebugReportReady: "Debug report ready — use the share sheet to save or copy.",
        .settingsImportConfig: "Import custom config (JSON)",
        .settingsExportDebug: "Export Debug Report",
        .settingsLegal: "Legal",
        .settingsDisclaimer: "Disclaimer",
        .settingsGPL: "GPL-3.0 License",
        .settingsNotices: "Open source notices",
        .settingsPrivacy: "Privacy",
        .settingsAbout: "About AzadiTunnel",
        .settingsSupport: "Support AzadiTunnel",
        .settingsLogs: "Logs",
        .helpBeastAuto: "Beast + Auto: smart fallback tries CDN fronting (Beast), then Direct.",
        .helpAuto: "Auto: smart fallback tries CDN fronting first, then Direct.",
        .helpConduitBlocked: "Conduit requires distributor keys in psiphon-config.local.json (see docs).",
        .helpConduit: "Conduit uses in-proxy WebRTC relays and community pairing. Reconnect after changes.",
        .helpCDN: "CDN uses FRONTED-MEEK-CDN protocols with built-in edge scan and dial overrides.",
        .helpDirect: "Direct uses the direct protocol set only.",
        .errorNoConfig: "No Psiphon config",
        .errorNoConfigSub: "Install bundled resources before connecting.",
        .errorConduitBlocked: "Conduit unavailable",
        .errorConduitBlockedSub: "Add distributor keys to psiphon-config.local.json. Auto and Beast still work.",
        .errorVPNPermission: "VPN permission",
        .errorVPNPermissionSub: "Allow VPN configuration in iOS Settings.",
        .errorOtherVpnBlocking: "Another VPN is active",
        .errorOtherVpnBlockingSub: "iOS allows only one VPN at a time. Open Settings → VPN, turn off the other VPN, then tap Connect here.",
        .openIOSSettings: "Open iOS Settings",
        .errorPsiphonFailed: "Tunnel failed",
        .errorPsiphonFailedSub: "Tunnel could not start. See Logs in Settings.",
        .errorInternetTest: "Internet test failed",
        .errorInternetTestSub: "generate_204 did not return HTTP 204.",
        .changeRegion: "Change region",
        .copyLogLine: "Copy line",
        .copyAllLogs: "Copy all logs",
        .clearLogs: "Clear logs",
        .clearLogsConfirm: "Remove all log entries from this device?",
        .refreshLogs: "Refresh",
        .logsCopiedTitle: "Copied",
        .supportIntro: "Optional tips and subscriptions help development. VPN features stay free.",
        .supportLoading: "Loading products…",
        .supportUnavailable: "Support purchases are not available in this build.",
        .supportRestore: "Restore Purchases",
        .supportStatus: "Status",
        .supportTipsSection: "One-time support",
        .supportSubscriptionsSection: "Subscriptions",
        .supportTipSmall: "Small tip",
        .supportTipMedium: "Medium tip",
        .supportTipLarge: "Large tip",
        .supportMonthly: "Monthly supporter",
        .supportYearly: "Yearly supporter",
        .supportStateNotPurchased: "No support purchase",
        .supportStatePurchased: "Thank you for your support",
        .supportStateSubscribed: "Active supporter subscription",
        .supportStateExpired: "Support subscription expired",
        .supportStateUnknown: "Unknown",
        .supportSubscriptionDisclaimer: "Subscriptions renew automatically unless cancelled at least 24 hours before the end of the current period. VPN features remain free with or without a purchase.",
        .supportManageSubscriptions: "Manage Subscriptions",
        .supportFreeBadge: "Core VPN · Always free",
        .aboutScreenTitle: "About",
        .aboutDeveloperLabel: "Company",
        .aboutDeveloperValue: "Debugsy Inc.",
        .aboutAppVersionLabel: "App Version",
        .aboutCoreVersionLabel: "Core Version",
        .aboutCoreVersionValue: "Psiphon + tun2socks",
        .aboutRateUs: "Rate Us",
        .aboutWebsite: "Psiphon (psiphon.ca)",
        .aboutPsiphonGitHub: "Psiphon on GitHub",
        .aboutCompanyWebsite: "Debugsy Inc.",
        .aboutX: "X",
        .aboutContactUs: "Contact Us",
        .aboutTerms: "Terms & Conditions",
        .aboutCopyright: "© %d Debugsy Inc. All rights reserved.",
        .aboutResponsibleUse: "Users are responsible for using the app lawfully and responsibly.",
        .aboutOpenSourceAck: "Open-source components are acknowledged in Legal & Open Source.",
        .legalOpenSourceTitle: "Legal & Open Source",
        .privacyNoticeTitle: "Privacy Notice",
        .beforeYouConnectTitle: "Before You Connect",
        .disclaimerIntro: "AzadiTunnel is a privacy-focused tunneling app designed to help users access a more open and reliable internet. Network behavior may vary depending on your location, provider, and local regulations.",
        .disclaimerResponsibleUseTitle: "Responsible use",
        .disclaimerResponsibleUse: "Use AzadiTunnel responsibly and only in ways that comply with applicable laws and the terms of services you use.",
        .disclaimerNoGuaranteeTitle: "No guarantee",
        .disclaimerNoGuarantee: "AzadiTunnel cannot guarantee uninterrupted access, complete anonymity, or protection against every type of network monitoring.",
        .disclaimerPrivacyDiagnosticsTitle: "Privacy and diagnostics",
        .disclaimerPrivacyDiagnostics: "The app may show connection logs, IP/DNS leak test results, quality reports, and diagnostic information to help you understand your connection. Do not share debug reports publicly unless you review them first.",
        .disclaimerNoIllegalContentTitle: "No built-in illegal content",
        .disclaimerNoIllegalContent: "AzadiTunnel does not provide illegal content and does not include preset paid servers in this build.",
        .disclaimerThirdPartyNetworksTitle: "Third-party networks",
        .disclaimerThirdPartyNetworks: "Some connection methods may rely on third-party infrastructure or open-source tunneling technologies. Availability and performance can change.",
        .iUnderstandAndAgree: "I Understand and Agree",
        .cancel: "Cancel",
        .viewFullLicenseNotices: "View Full License Notices",
        .legalAppLicenseSection: "App license",
        .legalOpenSourceComponentsSection: "Open-source acknowledgements",
        .legalGplWarningSection: "GPL / copyleft notice",
        .legalGplWarningBody: "Some components may be licensed under GPLv3. If GPLv3 code is included, the complete corresponding source code and license notices must be provided as required by the GPLv3 license.",
        .legalLicenseUnavailable: "License information is not available in this build.",
        .legalLicenseLabel: "License",
        .privacyNoticeBody: "AzadiTunnel is designed to minimize data collection. The app stores your tunnel settings locally on your device. Debug logs may include connection status, selected transport, protocol names, public IP test results, DNS test results, and device/app version information. Debug reports remove secrets before export.",
        .privacyNoticeNoSecrets: "We do not intentionally log private keys, server entry signature keys, obfuscation keys, user tokens, or full raw configs containing secrets.",
        .privacyNoticeReviewExport: "If you export a debug report, review it before sharing.",
        .privacyNoticeStoreKit: "Support purchases, if available, are handled by Apple through StoreKit.",
        .shareProxyRowTitle: "Share Proxy on Local Network",
        .shareProxyRowSubtitle: "Use this iPhone as a proxy gateway for devices on the same Wi-Fi.",
        .shareProxyNavTitle: "Share Proxy on Local Network",
        .shareProxyEnableTitle: "Enable Local Network Proxy Sharing",
        .shareProxyEnableDescription: "Allow devices on the same Wi-Fi network to use this iPhone as a proxy while AzadiTunnel is connected.",
        .shareProxyTrustedNetworkWarning: "Only enable this on trusted Wi-Fi networks. Other devices on the same network may be able to connect to your proxy.",
        .shareProxyStatusSection: "Status",
        .shareProxyStatusRunning: "Running",
        .shareProxyStatusStopped: "Stopped",
        .shareProxyStatusVpnDisconnected: "VPN disconnected",
        .shareProxyStatusNoWifi: "No Wi-Fi IP found",
        .shareProxyStatusPortInUse: "Port already in use",
        .shareProxyStatusFailed: "Failed to start",
        .shareProxyWifiIP: "Wi-Fi IP",
        .shareProxyNoWifiIP: "—",
        .shareProxyNoWifiHint: "No Wi-Fi IP found. Connect to Wi-Fi first.",
        .shareProxyAddressSection: "Proxy addresses",
        .shareProxyHttpAddressTitle: "HTTP Proxy",
        .shareProxySocksAddressTitle: "SOCKS5 Proxy",
        .shareProxyAddressUnavailable: "Unavailable",
        .shareProxyPortsSection: "Port settings",
        .shareProxyHttpPort: "HTTP Port",
        .shareProxySocksPort: "SOCKS5 Port",
        .shareProxySavePorts: "Save Ports",
        .shareProxyPortsSaved: "Ports saved",
        .shareProxyPortOutOfRange: "Port must be between 1024 and 65535.",
        .shareProxyPortsMustDiffer: "HTTP and SOCKS5 ports cannot be the same.",
        .shareProxyPortHint: "Defaults: HTTP 8087, SOCKS5 1088.",
        .shareProxyAuthSection: "Authentication",
        .shareProxyAuthToggle: "Enable authentication",
        .shareProxyUsername: "Username",
        .shareProxyPassword: "Password",
        .shareProxyNoAuthWarning: "No password protection is currently enabled. Anyone on the same Wi-Fi network may be able to use this proxy while it is running.",
        .shareProxySecuritySection: "Security",
        .shareProxySecurityWarning: "Security warning: This feature exposes a proxy server to your local Wi-Fi network. Only use it on trusted networks such as your home Wi-Fi. Do not enable it on public Wi-Fi.",
        .shareProxyInstructionsSection: "How to connect another device",
        .shareProxyHowToiPhone: "iPhone / iPad",
        .shareProxyHowToAndroid: "Android",
        .shareProxyHowToWindows: "Windows",
        .shareProxyHowToAndroidTV: "Android TV",
        .shareProxyInstructionsiPhone: """
1. Connect the other iPhone/iPad to the same Wi-Fi.
2. Open Settings.
3. Tap Wi-Fi.
4. Tap the info button next to your Wi-Fi network.
5. Scroll to HTTP Proxy.
6. Select Manual.
7. Server: enter this iPhone's Wi-Fi IP.
8. Port: enter 8087 or your custom HTTP port.
9. Save and open Safari to test.
""",
        .shareProxyInstructionsAndroid: """
1. Connect the Android phone to the same Wi-Fi.
2. Open Wi-Fi settings.
3. Tap your connected Wi-Fi network.
4. Open Advanced settings or Proxy settings.
5. Set Proxy to Manual.
6. Proxy hostname: enter this iPhone's Wi-Fi IP.
7. Proxy port: enter 8087 or your custom HTTP port.
8. Save and test in browser.
""",
        .shareProxyInstructionsWindows: """
1. Connect Windows to the same Wi-Fi.
2. Open Settings.
3. Go to Network & Internet.
4. Open Proxy.
5. Turn on Manual proxy setup.
6. Address: enter this iPhone's Wi-Fi IP.
7. Port: enter 8087 or your custom HTTP port.
8. Save and test in browser.
""",
        .shareProxyInstructionsAndroidTV: """
1. Connect Android TV to the same Wi-Fi.
2. Open Settings.
3. Go to Network & Internet.
4. Select your Wi-Fi network.
5. Open Proxy settings if available.
6. Choose Manual.
7. Proxy hostname: enter this iPhone's Wi-Fi IP.
8. Proxy port: enter 8087 or your custom HTTP port.
9. Save and test with an app/browser.
""",
        .shareProxySocksNoteTitle: "SOCKS5 note",
        .shareProxySocksNoteBody: "Some devices do not support SOCKS5 in system Wi-Fi settings. For SOCKS5, use an app/browser/player that supports SOCKS5 manually and enter the iPhone's Wi-Fi IP as the host and 1088 (or your custom SOCKS5 port) as the port.",
        .proxyOnlyRowTitle: "Proxy Only Mode",
        .proxyOnlyRowSubtitle: "Only apps configured to use the local HTTP/SOCKS proxy will go through AzadiTunnel.",
        .proxyOnlyNavTitle: "Proxy Only Mode",
        .proxyOnlyEnableTitle: "Proxy Only Mode",
        .proxyOnlyEnableDescription: "Only apps configured to use the local HTTP/SOCKS proxy will go through AzadiTunnel. Other traffic will stay direct.",
        .proxyOnlyWarningShort: "This is not full-device VPN protection. Apps that are not configured to use the proxy will bypass AzadiTunnel.",
        .proxyOnlyWarningFull: "Proxy Only Mode does not protect all apps. Only apps configured with this proxy will use AzadiTunnel.",
        .proxyOnlyWarningDashboard: "Proxy Only — not full-device protection. Only configured apps use AzadiTunnel.",
        .proxyOnlyModeSection: "Mode",
        .proxyOnlyModeFullVPN: "Full VPN",
        .proxyOnlyModeProxyOnly: "Proxy Only",
        .proxyOnlyLocalAddresses: "Local proxy (this iPhone)",
        .proxyOnlyLanAddresses: "LAN proxy (other devices)",
        .proxyOnlyStatusConnected: "Proxy Only",
        .proxyOnlyReconnectHint: "Reconnect for this change to take effect.",
        .proxyOnlyConfiguredAppsHint: "On this iPhone, use your Wi-Fi IP (not 127.0.0.1). Example: SOCKS5 <Wi-Fi-IP>:1088 or HTTP <Wi-Fi-IP>:8087.",
        .proxyOnlySameDeviceAddresses: "Same iPhone (use Wi-Fi IP)",
        .proxyOnlyLoopbackNotReachable: "127.0.0.1 does not work from other apps. The proxy runs inside the VPN extension; Telegram and other apps must use this iPhone's Wi-Fi IP instead.",
        .proxyOnlySocksSelfTestTitle: "SOCKS5 reachability test",
        .proxyOnlySocksSelfTestButton: "Test SOCKS5 from this app",
        .proxyOnlySocksSelfTestRunning: "Testing…",
        .proxyOnlyTelegramHint: "In Telegram → Settings → Data and Storage → Proxy: set SOCKS5 to your Wi-Fi IP and port 1088 (not 127.0.0.1).",
        .proxyOnlyNoWifiSameDevice: "Connect to Wi-Fi to use Proxy Only from apps on this iPhone. Cellular-only may not reach the extension proxy.",
        .proxyOnlyPublicIPUnavailable: "Proxy IP unavailable",
        .proxyOnlySocksSelfTestWifiOK: "SOCKS5 reachable via Wi-Fi IP",
        .proxyOnlySocksSelfTestWifiFailed: "SOCKS5 not reachable via Wi-Fi IP",
        .proxyOnlySocksSelfTestNoWifi: "Wi-Fi IP unavailable — connect to Wi-Fi first.",
        .proxyOnlyRequiresWifiTitle: "Wi-Fi required",
        .proxyOnlyRequiresWifiMessage: "Proxy Only Mode requires Wi-Fi. Same-device SOCKS/HTTP proxy cannot work on cellular because there is no reachable Wi-Fi IP. Please connect to Wi-Fi or turn off Proxy Only Mode.",
        .proxyOnlyTurnOffMode: "Turn Off Proxy Only Mode",
        .proxyOnlyNotAvailableOnCellular: "Not available on cellular. Connect to Wi-Fi to use Proxy Only Mode.",
        .bypassRowTitle: "Bypass Iranian IPs",
        .bypassRowSubtitle: "Send Iranian destination IPs directly, outside the VPN tunnel.",
        .bypassNavTitle: "Bypass Iranian IPs",
        .bypassEnableTitle: "Bypass Iranian IPs",
        .bypassEnableDescription: "When on, Iranian IP ranges go directly through your normal network while everything else stays in the AzadiTunnel VPN. Applies on the next connect.",
        .bypassStatusSection: "Status",
        .bypassListCount: "Iran IP ranges",
        .bypassListUpdated: "List updated",
        .bypassRoutesApplied: "Routes applied",
        .bypassNever: "Never",
        .bypassUpdateListNow: "Update list now",
        .bypassUpdating: "Updating…",
        .bypassListUpdatedToast: "Iran IP list updated.",
        .bypassListFailedToast: "Could not update the list. Using cached list if available.",
        .bypassCustomSection: "Custom bypass IPs / ranges",
        .bypassCustomPlaceholder: "1.2.3.4 or 1.2.3.0/24 (one per line)",
        .bypassCustomHint: "Add individual IPs or CIDR ranges to bypass the VPN. One entry per line.",
        .bypassDomainSection: "Bypass domains (experimental)",
        .bypassDomainPlaceholder: "example.ir (one per line)",
        .bypassDomainHint: "Domains are resolved to IP addresses and added as bypass routes.",
        .bypassResolveNow: "Resolve domains now",
        .bypassResolving: "Resolving…",
        .bypassDomainWarning: "Domain bypass is unreliable for sites behind CDNs or with frequently changing IPs. Resolved IPs are cached and refreshed periodically.",
        .bypassSaveApply: "Save & apply",
        .bypassSavedToast: "Bypass settings saved.",
        .bypassEffectiveNote: "By default, bypass works at the IP layer and keeps normal VPN behavior. Use Strict IP bypass mode above to also cover apps that use the system HTTP proxy (experimental).",
        .bypassReconnectNote: "Changes apply on the next connect. Reconnect to apply them now.",
        .bypassNoListWarning: "Iran bypass list is not available. VPN will continue normally.",
        .bypassListSourceBundled: "Using built-in list (no update downloaded yet).",
        .bypassBestEffortWarning: "Some apps that use the system HTTP proxy may not respect IP bypass. Apps routed through tun2socks can still use bypass.",
        .bypassStrictSection: "Advanced",
        .bypassStrictToggle: "Strict IP bypass mode (experimental)",
        .bypassStrictDescription: "Disables the in-tunnel system HTTP proxy so IP bypass routes apply to all apps, including HTTPS. This can break general internet access and public-IP checks in some setups. Leave off unless you know you need it.",
        .messagingCompatRowTitle: "Messaging apps compatibility",
        .messagingCompatRowSubtitle: "Telegram & WhatsApp fixes (MTU, DNS, routing)",
        .messagingCompatNavTitle: "Messaging apps",
        .messagingCompatToggle: "Compatibility mode",
        .messagingCompatDescription: "Helps Telegram and WhatsApp when websites work but messaging fails. Lowers MTU, keeps messaging traffic in the tunnel, enables safe DNS if off, and retries CDN/Direct transports on connect.",
        .messagingCompatMtuSection: "Tunnel MTU",
        .messagingCompatMtu: "MTU",
        .messagingCompatMtuHint: "Try 1200 or 1240 if WhatsApp chat (port 5222) fails; 1280 is the default.",
        .messagingCompatFeaturesSection: "When enabled",
        .messagingCompatFeatureBypass: "Blocks bypass routes for Telegram/WhatsApp IPs",
        .messagingCompatFeatureDns: "Uses Cloudflare DoH when Secure DNS is off",
        .messagingCompatFeatureFallback: "Retries CDN, Auto+Beast, and Direct on connect",
        .messagingCompatFeatureUdpNote: "Voice/video UDP is not relayed (iOS tun2socks is TCP-only). Calls may still fail.",
        .messagingCompatReconnectNote: "Reconnect the VPN after changing this setting.",
        .secureDnsRowTitle: "Secure DNS",
        .secureDnsRowSubtitle: "Optional DoH/DoT DNS resolver",
        .secureDnsNavTitle: "Secure DNS",
        .secureDnsModeSection: "Mode",
        .secureDnsModeOff: "Off",
        .secureDnsModeDoh: "DoH",
        .secureDnsModeDot: "DoT",
        .secureDnsModeOffDetail: "Keep your current VPN DNS behavior",
        .secureDnsModeDohDetail: "Encrypted DNS over HTTPS through the tunnel",
        .secureDnsModeDotDetail: "Encrypted DNS over TLS through the tunnel",
        .secureDnsActiveSelection: "Selected",
        .secureDnsProviderSection: "Provider",
        .secureDnsProviderCloudflare: "Cloudflare",
        .secureDnsProviderGoogle: "Google",
        .secureDnsProviderQuad9: "Quad9",
        .secureDnsProviderAdguard: "AdGuard",
        .secureDnsProviderCustom: "Custom",
        .secureDnsCustomDoHURL: "Custom DoH URL",
        .secureDnsCustomDoTHost: "Custom DoT host",
        .secureDnsBlockCleartext: "Block cleartext DNS",
        .secureDnsBlockCleartextHint: "When Secure DNS fails, do not fall back to legacy DNS. DNS queries may fail until the resolver works again.",
        .secureDnsTestButton: "Test DNS",
        .secureDnsTestRunning: "Testing DNS…",
        .secureDnsTestOk: "Secure DNS test passed",
        .secureDnsTestFailed: "Secure DNS test failed",
        .secureDnsTestConnectFirst: "Connect VPN first to test Secure DNS through the tunnel.",
        .secureDnsWarningSection: "Warning",
        .secureDnsDefaultOffNote: "Secure DNS is off by default. Your current VPN DNS behavior is unchanged until you enable DoH or DoT.",
        .secureDnsReconnectNote: "Reconnect for Secure DNS changes to take effect.",
        .secureDnsProxyOnlyNote: "Secure DNS applies to Full VPN mode only. Proxy Only mode is unchanged.",
        .secureDnsBlockedWarning: "Secure DNS failed and cleartext DNS is blocked. Check your resolver settings or turn off “Block cleartext DNS”.",
        .secureDnsTestHint: "The in-app DNS test resolves example.com through the tunnel using your selected DoH or DoT provider. Check extension logs for SECURE_DNS_TEST_OK and SECURE_DNS_DOH_QUERY_OK / SECURE_DNS_DOT_QUERY_OK."
    ]

    private static let fa: [AppLanguageController.L10nKey: String] = [
        .supportButton: "حمایت",
        .splashTagline: "تونل متمرکز بر حریم خصوصی برای اینترنت بازتر",
        .diagnosticsSection: "تشخیص اتصال",
        .vpnPing: "پینگ",
        .refreshPing: "بازخوانی پینگ",
        .copy: "کپی",
        .copiedToClipboard: "در کلیپ‌بورد کپی شد",
        .testPass: "موفق",
        .testFail: "ناموفق",
        .configSetupBanner: "پیکربندی Psiphon بستهٔ داخلی موجود یا نامعتبر است. تنظیمات → پیشرفته → نصب مجدد بسته.",
        .onboardingNavTitle: "خوش آمدید",
        .onboardingWelcomeTitle: "به AzadiTunnel خوش آمدید",
        .onboardingWelcomeBody: "AzadiTunnel ترافیک دستگاه را از تونل رمزگذاری‌شده Psiphon عبور می‌دهد تا اپ‌ها به اینترنت بازتر دسترسی داشته باشند.",
        .onboardingPrivacyTitle: "حریم خصوصی",
        .onboardingPrivacyBody: "تشخیص‌ها روی دستگاه می‌ماند. گزارش اشکال‌زدایی فقط با انتخاب شما صادر می‌شود.",
        .onboardingTransportTitle: "حالت‌های حمل‌ونقل",
        .onboardingTransportBody: "در تنظیمات Auto، Direct، CDN fronting یا Conduit را انتخاب کنید. Beast برقراری تونل را تسریع می‌کند.",
        .onboardingFallbackTitle: "جایگزین هوشمند",
        .onboardingFallbackBody: "اگر CDN fronting ناموفق باشد، اپ می‌تواند Auto+Beast و سپس Direct را امتحان کند.",
        .onboardingSupportTitle: "حمایت از توسعه",
        .onboardingSupportBody: "قابلیت VPN رایگان می‌ماند. انعام و اشتراک اختیاری از صفحهٔ اصلی در دسترس است.",
        .onboardingContinue: "ادامه",
        .onboardingGetStarted: "شروع",
        .onboardingSkip: "رد کردن",
        .protocolAuto: "خودکار",
        .protocolDirect: "مستقیم",
        .protocolCDN: "CDN fronting",
        .protocolConduit: "کندویت",
        .conduitModeAuto: "خودکار (جامعه سپس عمومی)",
        .conduitModeCommunity: "جامعه",
        .conduitModePublic: "عمومی",
        .settingsConnection: "اتصال",
        .settingsConfigSource: "منبع پیکربندی",
        .settingsBundled: "بستهٔ داخلی",
        .settingsCustom: "سفارشی",
        .settingsServerEntries: "ورودی‌های سرور",
        .settingsRegion: "منطقه",
        .settingsEgressRegion: "منطقه خروجی",
        .settingsRegionHint: "منطقه در اتصال بعدی اعمال می‌شود.",
        .settingsTransport: "حمل‌ونقل",
        .settingsProtocol: "پروتکل",
        .settingsBeastMode: "حالت Beast",
        .settingsConduitMode: "حالت Conduit",
        .settingsBlockCensored: "مسدودسازی رله کشورهای سانسورشده",
        .settingsConduitTimeout: "مهلت جایگزین خودکار",
        .settingsCDNFronting: "CDN fronting",
        .settingsCDNExpert: "تنظیمات پیشرفته IP لبه، SNI و اسکن CDN.",
        .settingsCDNBuiltinScan: "اسکن CDN داخلی",
        .settingsCDNEdgeIPs: "IP لبه CDN",
        .settingsCDNSNI: "نام‌های SNI",
        .settingsCDNEdgesSummary: "لبه‌های داخلی",
        .settingsProxy: "پروکسی بالادست",
        .settingsProxyEnable: "فعال‌سازی پروکسی",
        .settingsProxyHost: "میزبان",
        .settingsProxyPort: "پورت",
        .settingsProxySystem: "پروکسی سیستم",
        .settingsBehavior: "رفتار",
        .settingsSmartFallback: "جایگزین هوشمند (CDN → Auto+Beast → Direct)",
        .settingsAutoRetryNoInternet: "بازیابی هوشمند (بدون اینترنت)",
        .settingsAutoRetryNoInternetHelp: "اگر تونل وصل شد ولی سایت باز نشد، خودکار مسیر ذخیره‌شده، CDN/Auto/Direct، منطقه خروجی، Beast، سازگاری پیام‌رسان و Conduit را امتحان می‌کند.",
        .settingsAutoReconnect: "اتصال مجدد خودکار",
        .settingsConnectOnLaunch: "اتصال هنگام اجرا",
        .settingsVPNOnDemand: "VPN On Demand",
        .settingsVPNOnDemandMode: "اتصال هنگام",
        .settingsVPNOnDemandHelp: "iOS با تطبیق قانون، تونل را خودکار وصل می‌کند. یک‌بار در صفحهٔ اصلی Connect را بزنید تا پروفایل VPN ساخته شود.",
        .onDemandAlways: "هر شبکه",
        .onDemandWiFi: "فقط Wi‑Fi",
        .onDemandCellular: "فقط سلولی",
        .settingsAdvanced: "پیشرفته / توسعه",
        .settingsAdvancedHint: "در صفحهٔ اصلی Connect را بزنید. وارد کردن اختیاری است.",
        .settingsRetryBundled: "نصب مجدد بستهٔ داخلی",
        .settingsRetryBundledFailed: "نصب بسته ناموفق بود — گزارش‌ها را ببینید.",
        .settingsResetDefaults: "بازنشانی تنظیمات به پیش‌فرض",
        .settingsResetDefaultsConfirmTitle: "بازنشانی تنظیمات؟",
        .settingsResetDefaultsConfirmMessage: "همهٔ تنظیمات اتصال و رفتار به حالت پیش‌فرض برمی‌گردند. زبان و پذیرش قوانین حفظ می‌شود. پیکربندی Psiphon واردشده تغییر نمی‌کند.",
        .settingsResetDefaultsDone: "تنظیمات به پیش‌فرض بازنشانی شد",
        .settingsBundledInstallSuccess: "پیکربندی بستهٔ داخلی با موفقیت نصب شد.",
        .settingsConfigImportSuccess: "پیکربندی سفارشی با موفقیت وارد شد.",
        .settingsConfigImportFailed: "وارد کردن پیکربندی ناموفق بود.",
        .settingsDebugReportReady: "گزارش اشکال‌زدایی آماده است — از اشتراک‌گذاری ذخیره یا کپی کنید.",
        .settingsImportConfig: "وارد کردن پیکربندی (JSON)",
        .settingsExportDebug: "صادرات گزارش اشکال‌زدایی",
        .settingsLegal: "حقوقی",
        .settingsDisclaimer: "سلب مسئولیت",
        .settingsGPL: "مجوز GPL-3.0",
        .settingsNotices: "اعلامیه‌های متن‌باز",
        .settingsPrivacy: "حریم خصوصی",
        .settingsAbout: "درباره AzadiTunnel",
        .settingsSupport: "حمایت از AzadiTunnel",
        .settingsLogs: "گزارش‌ها",
        .helpBeastAuto: "Beast + Auto: جایگزین هوشمند اول CDN fronting (Beast)، بعد Direct.",
        .helpAuto: "Auto: جایگزین هوشمند اول CDN fronting، بعد Direct.",
        .helpConduitBlocked: "Conduit به کلیدهای توزیع‌کننده در psiphon-config.local.json نیاز دارد.",
        .helpConduit: "Conduit از رله WebRTC و جفت‌سازی جامعه استفاده می‌کند.",
        .helpCDN: "CDN از پروتکل‌های FRONTED-MEEK-CDN با اسکن لبه استفاده می‌کند.",
        .helpDirect: "Direct فقط مجموعه پروتکل مستقیم.",
        .errorNoConfig: "بدون پیکربندی Psiphon",
        .errorNoConfigSub: "قبل از اتصال منابع بسته را نصب کنید.",
        .errorConduitBlocked: "Conduit در دسترس نیست",
        .errorConduitBlockedSub: "کلیدهای توزیع‌کننده را اضافه کنید. Auto و Beast کار می‌کنند.",
        .errorVPNPermission: "مجوز VPN",
        .errorVPNPermissionSub: "در تنظیمات iOS مجوز VPN را بدهید.",
        .errorOtherVpnBlocking: "VPN دیگری فعال است",
        .errorOtherVpnBlockingSub: "iOS فقط یک VPN هم‌زمان اجازه می‌دهد. تنظیمات → VPN را باز کنید، VPN دیگر را خاموش کنید، بعد اینجا Connect بزنید.",
        .openIOSSettings: "باز کردن تنظیمات iOS",
        .errorPsiphonFailed: "خطای تونل",
        .errorPsiphonFailedSub: "تونل شروع نشد. گزارش‌ها را در تنظیمات ببینید.",
        .errorInternetTest: "آزمون اینترنت ناموفق",
        .errorInternetTestSub: "generate_204 کد 204 برنگرداند.",
        .changeRegion: "تغییر منطقه",
        .copyLogLine: "کپی خط",
        .copyAllLogs: "کپی همه",
        .clearLogs: "پاک کردن گزارش‌ها",
        .clearLogsConfirm: "همهٔ خطوط گزارش از این دستگاه حذف شوند؟",
        .refreshLogs: "بازخوانی",
        .logsCopiedTitle: "کپی شد",
        .supportIntro: "انعام و اشتراک اختیاری به توسعه کمک می‌کند. VPN رایگان می‌ماند.",
        .supportLoading: "در حال بارگذاری محصولات…",
        .supportUnavailable: "خرید پشتیبانی در این نسخه در دسترس نیست.",
        .supportRestore: "بازیابی خریدها",
        .supportStatus: "وضعیت",
        .supportTipsSection: "پشتیبانی یک‌بار",
        .supportSubscriptionsSection: "اشتراک",
        .supportTipSmall: "انعام کوچک",
        .supportTipMedium: "انعام متوسط",
        .supportTipLarge: "انعام بزرگ",
        .supportMonthly: "حامی ماهانه",
        .supportYearly: "حامی سالانه",
        .supportStateNotPurchased: "بدون خرید پشتیبانی",
        .supportStatePurchased: "از حمایت شما سپاسگزاریم",
        .supportStateSubscribed: "اشتراک حمایت فعال",
        .supportStateExpired: "اشتراک حمایت منقضی شده",
        .supportStateUnknown: "نامشخص",
        .supportSubscriptionDisclaimer: "اشتراک‌ها به‌صورت خودکار تمدید می‌شوند مگر حداقل ۲۴ ساعت قبل از پایان دوره لغو شوند. VPN با یا بدون خرید رایگان می‌ماند.",
        .supportManageSubscriptions: "مدیریت اشتراک‌ها",
        .supportFreeBadge: "VPN اصلی · همیشه رایگان",
        .aboutScreenTitle: "درباره",
        .aboutDeveloperLabel: "شرکت",
        .aboutDeveloperValue: "Debugsy Inc.",
        .aboutAppVersionLabel: "نسخهٔ اپ",
        .aboutCoreVersionLabel: "نسخهٔ هسته",
        .aboutCoreVersionValue: "Psiphon + tun2socks",
        .aboutRateUs: "امتیازدهی",
        .aboutWebsite: "Psiphon (psiphon.ca)",
        .aboutPsiphonGitHub: "Psiphon در GitHub",
        .aboutCompanyWebsite: "Debugsy Inc.",
        .aboutX: "X",
        .aboutContactUs: "تماس با ما",
        .aboutTerms: "شرایط و ضوابط",
        .aboutCopyright: "© %d Debugsy Inc. تمامی حقوق محفوظ است.",
        .aboutResponsibleUse: "کاربران مسئول استفادهٔ قانونی و مسئولانه از اپ هستند.",
        .aboutOpenSourceAck: "اجزای متن‌باز در «حقوقی و متن‌باز» ذکر شده‌اند.",
        .legalOpenSourceTitle: "حقوقی و متن‌باز",
        .privacyNoticeTitle: "اطلاعیهٔ حریم خصوصی",
        .beforeYouConnectTitle: "قبل از اتصال",
        .disclaimerIntro: "AzadiTunnel یک اپ تونل متمرکز بر حریم خصوصی است که برای دسترسی بازتر و پایدارتر به اینترنت طراحی شده است. رفتار شبکه بسته به موقعیت، ارائه‌دهنده و مقررات محلی متفاوت است.",
        .disclaimerResponsibleUseTitle: "استفادهٔ مسئولانه",
        .disclaimerResponsibleUse: "AzadiTunnel را مسئولانه و فقط مطابق قوانین و شرایط سرویس‌هایی که استفاده می‌کنید به کار ببرید.",
        .disclaimerNoGuaranteeTitle: "بدون تضمین",
        .disclaimerNoGuarantee: "AzadiTunnel نمی‌تواند دسترسی بدون وقفه، ناشناس بودن کامل یا محافظت در برابر همهٔ انواع پایش شبکه را تضمین کند.",
        .disclaimerPrivacyDiagnosticsTitle: "حریم خصوصی و تشخیص",
        .disclaimerPrivacyDiagnostics: "اپ ممکن است گزارش اتصال، نتایج آزمون نشت IP/DNS، گزارش کیفیت و اطلاعات تشخیصی نشان دهد. گزارش اشکال‌زدایی را بدون بازبینی عمومی نکنید.",
        .disclaimerNoIllegalContentTitle: "بدون محتوای غیرقانونی داخلی",
        .disclaimerNoIllegalContent: "AzadiTunnel محتوای غیرقانونی ارائه نمی‌دهد و سرور پولی از پیش تنظیم‌شده در این نسخه ندارد.",
        .disclaimerThirdPartyNetworksTitle: "شبکه‌های شخص ثالث",
        .disclaimerThirdPartyNetworks: "برخی روش‌های اتصال ممکن است به زیرساخت شخص ثالث یا فناوری تونل متن‌باز وابسته باشند. دسترس‌پذیری و عملکرد می‌تواند تغییر کند.",
        .iUnderstandAndAgree: "می‌فهمم و موافقم",
        .cancel: "لغو",
        .viewFullLicenseNotices: "مشاهدهٔ اطلاعیه‌های کامل مجوز",
        .legalAppLicenseSection: "مجوز اپ",
        .legalOpenSourceComponentsSection: "سپاس متن‌باز",
        .legalGplWarningSection: "اطلاعیهٔ GPL / copyleft",
        .legalGplWarningBody: "برخی اجزا ممکن است تحت GPLv3 باشند. در صورت شامل بودن کد GPLv3، ارائهٔ سورس کامل و اطلاعیه‌های مجوز طبق GPLv3 لازم است.",
        .legalLicenseUnavailable: "اطلاعات مجوز در این نسخه در دسترس نیست.",
        .legalLicenseLabel: "مجوز",
        .privacyNoticeBody: "AzadiTunnel برای کمینه کردن جمع‌آوری داده طراحی شده است. تنظیمات تونل روی دستگاه شما ذخیره می‌شود. گزارش اشکال‌زدایی ممکن است وضعیت اتصال، حمل‌ونقل، پروتکل، IP عمومی، DNS و نسخهٔ اپ/دستگاه را شامل شود. گزارش‌ها قبل از صادرات پاک‌سازی می‌شوند.",
        .privacyNoticeNoSecrets: "عمداً کلیدهای خصوصی، کلیدهای امضای server entry، کلید obfuscation، توکن کاربر یا پیکربندی خام کامل حاوی راز را ثبت نمی‌کنیم.",
        .privacyNoticeReviewExport: "قبل از اشتراک‌گذاری گزارش اشکال‌زدایی، آن را بازبینی کنید.",
        .privacyNoticeStoreKit: "خریدهای پشتیبانی، در صورت وجود، از طریق StoreKit اپل انجام می‌شود.",
        .shareProxyRowTitle: "اشتراک پروکسی روی شبکه محلی",
        .shareProxyRowSubtitle: "از این آیفون به‌عنوان دروازهٔ پروکسی برای دستگاه‌های هم‌شبکه استفاده کنید.",
        .shareProxyNavTitle: "اشتراک پروکسی روی شبکه محلی",
        .shareProxyEnableTitle: "فعال‌سازی اشتراک پروکسی در شبکه محلی",
        .shareProxyEnableDescription: "اجازه می‌دهد دستگاه‌های هم‌شبکه از این آیفون به‌عنوان پروکسی استفاده کنند، در حالی که AzadiTunnel متصل است.",
        .shareProxyTrustedNetworkWarning: "فقط روی شبکه‌های Wi-Fi مورد اعتماد فعال کنید. دستگاه‌های دیگر روی همان شبکه ممکن است بتوانند به پروکسی شما وصل شوند.",
        .shareProxyStatusSection: "وضعیت",
        .shareProxyStatusRunning: "در حال اجرا",
        .shareProxyStatusStopped: "متوقف",
        .shareProxyStatusVpnDisconnected: "VPN قطع است",
        .shareProxyStatusNoWifi: "آدرس Wi-Fi پیدا نشد",
        .shareProxyStatusPortInUse: "پورت قبلاً استفاده شده",
        .shareProxyStatusFailed: "اجرا ناموفق بود",
        .shareProxyWifiIP: "آدرس IP وای‌فای",
        .shareProxyNoWifiIP: "—",
        .shareProxyNoWifiHint: "آدرس Wi-Fi پیدا نشد. ابتدا به Wi-Fi وصل شوید.",
        .shareProxyAddressSection: "آدرس‌های پروکسی",
        .shareProxyHttpAddressTitle: "پروکسی HTTP",
        .shareProxySocksAddressTitle: "پروکسی SOCKS5",
        .shareProxyAddressUnavailable: "در دسترس نیست",
        .shareProxyPortsSection: "تنظیمات پورت",
        .shareProxyHttpPort: "پورت HTTP",
        .shareProxySocksPort: "پورت SOCKS5",
        .shareProxySavePorts: "ذخیره پورت‌ها",
        .shareProxyPortsSaved: "پورت‌ها ذخیره شد",
        .shareProxyPortOutOfRange: "پورت باید بین ۱۰۲۴ تا ۶۵۵۳۵ باشد.",
        .shareProxyPortsMustDiffer: "پورت HTTP و SOCKS5 نمی‌توانند یکسان باشند.",
        .shareProxyPortHint: "پیش‌فرض: HTTP ۸۰۸۷، SOCKS5 ۱۰۸۸.",
        .shareProxyAuthSection: "احراز هویت",
        .shareProxyAuthToggle: "فعال‌سازی احراز هویت",
        .shareProxyUsername: "نام کاربری",
        .shareProxyPassword: "گذرواژه",
        .shareProxyNoAuthWarning: "در حال حاضر محافظت با گذرواژه فعال نیست. هر کسی روی همان Wi-Fi ممکن است بتواند از این پروکسی استفاده کند.",
        .shareProxySecuritySection: "امنیت",
        .shareProxySecurityWarning: "هشدار امنیتی: این قابلیت یک سرور پروکسی را روی شبکهٔ Wi-Fi محلی شما در دسترس قرار می‌دهد. فقط روی شبکه‌های مورد اعتماد مانند Wi-Fi خانه استفاده کنید. روی Wi-Fi عمومی فعال نکنید.",
        .shareProxyInstructionsSection: "راهنمای اتصال دستگاه دیگر",
        .shareProxyHowToiPhone: "آیفون / آیپد",
        .shareProxyHowToAndroid: "اندروید",
        .shareProxyHowToWindows: "ویندوز",
        .shareProxyHowToAndroidTV: "اندروید TV",
        .shareProxyInstructionsiPhone: """
۱. آیفون/آیپد دیگر را به همان Wi-Fi وصل کنید.
۲. Settings (تنظیمات) را باز کنید.
۳. روی Wi-Fi بزنید.
۴. روی دکمهٔ info کنار نام شبکهٔ Wi-Fi بزنید.
۵. تا HTTP Proxy پایین بروید.
۶. Manual را انتخاب کنید.
۷. در Server آدرس Wi-Fi این آیفون را وارد کنید.
۸. در Port مقدار ۸۰۸۷ یا پورت HTTP سفارشی‌تان را وارد کنید.
۹. ذخیره و سپس Safari را برای آزمایش باز کنید.
""",
        .shareProxyInstructionsAndroid: """
۱. گوشی اندروید را به همان Wi-Fi وصل کنید.
۲. تنظیمات Wi-Fi را باز کنید.
۳. روی نام شبکهٔ متصل‌شده بزنید.
۴. Advanced یا Proxy settings را باز کنید.
۵. Proxy را روی Manual بگذارید.
۶. در Proxy hostname آدرس Wi-Fi این آیفون را وارد کنید.
۷. در Proxy port مقدار ۸۰۸۷ یا پورت HTTP سفارشی‌تان را وارد کنید.
۸. ذخیره کنید و در مرورگر آزمایش کنید.
""",
        .shareProxyInstructionsWindows: """
۱. ویندوز را به همان Wi-Fi وصل کنید.
۲. Settings را باز کنید.
۳. به Network & Internet بروید.
۴. بخش Proxy را باز کنید.
۵. Manual proxy setup را روشن کنید.
۶. در Address آدرس Wi-Fi این آیفون را وارد کنید.
۷. در Port مقدار ۸۰۸۷ یا پورت HTTP سفارشی‌تان را وارد کنید.
۸. ذخیره کنید و در مرورگر آزمایش کنید.
""",
        .shareProxyInstructionsAndroidTV: """
۱. اندروید TV را به همان Wi-Fi وصل کنید.
۲. Settings را باز کنید.
۳. به Network & Internet بروید.
۴. شبکهٔ Wi-Fi خود را انتخاب کنید.
۵. در صورت وجود، Proxy settings را باز کنید.
۶. Manual را انتخاب کنید.
۷. در Proxy hostname آدرس Wi-Fi این آیفون را وارد کنید.
۸. در Proxy port مقدار ۸۰۸۷ یا پورت HTTP سفارشی‌تان را وارد کنید.
۹. ذخیره کنید و با یک اپ/مرورگر آزمایش کنید.
""",
        .shareProxySocksNoteTitle: "نکتهٔ SOCKS5",
        .shareProxySocksNoteBody: "بعضی دستگاه‌ها در تنظیمات Wi-Fi سیستم از SOCKS5 پشتیبانی نمی‌کنند. برای SOCKS5 از یک اپ/مرورگر/پخش‌کننده که SOCKS5 را پشتیبانی می‌کند استفاده کنید و آدرس Wi-Fi این آیفون را به‌عنوان Host و ۱۰۸۸ (یا پورت SOCKS5 سفارشی) را به‌عنوان Port وارد کنید.",
        .proxyOnlyRowTitle: "حالت فقط پروکسی",
        .proxyOnlyRowSubtitle: "فقط اپ‌هایی که پروکسی HTTP/SOCKS محلی را تنظیم کرده‌اند از AzadiTunnel استفاده می‌کنند.",
        .proxyOnlyNavTitle: "حالت فقط پروکسی",
        .proxyOnlyEnableTitle: "حالت فقط پروکسی",
        .proxyOnlyEnableDescription: "فقط اپ‌هایی که پروکسی HTTP/SOCKS محلی را تنظیم کرده‌اند از AzadiTunnel استفاده می‌کنند. بقیهٔ ترافیک مستقیم می‌ماند.",
        .proxyOnlyWarningShort: "این حفاظت VPN برای کل دستگاه نیست. اپ‌هایی که پروکسی را تنظیم نکرده‌اند از AzadiTunnel عبور نمی‌کنند.",
        .proxyOnlyWarningFull: "حالت فقط پروکسی همهٔ اپ‌ها را محافظت نمی‌کند. فقط اپ‌هایی که این پروکسی را تنظیم کرده‌اند از AzadiTunnel استفاده می‌کنند.",
        .proxyOnlyWarningDashboard: "فقط پروکسی — حفاظت کامل دستگاه نیست. فقط اپ‌های پیکربندی‌شده از AzadiTunnel استفاده می‌کنند.",
        .proxyOnlyModeSection: "حالت",
        .proxyOnlyModeFullVPN: "VPN کامل",
        .proxyOnlyModeProxyOnly: "فقط پروکسی",
        .proxyOnlyLocalAddresses: "پروکسی محلی (این آیفون)",
        .proxyOnlyLanAddresses: "پروکسی LAN (دستگاه‌های دیگر)",
        .proxyOnlyStatusConnected: "فقط پروکسی",
        .proxyOnlyReconnectHint: "برای اعمال این تغییر دوباره وصل شوید.",
        .proxyOnlyConfiguredAppsHint: "روی همین آیفون از آدرس Wi-Fi استفاده کنید (نه 127.0.0.1). مثال: SOCKS5 <آدرس-Wi-Fi>:1088 یا HTTP <آدرس-Wi-Fi>:8087.",
        .proxyOnlySameDeviceAddresses: "همین آیفون (از IP وای‌فای استفاده کنید)",
        .proxyOnlyLoopbackNotReachable: "127.0.0.1 از اپ‌های دیگر کار نمی‌کند. پروکسی داخل افزونهٔ VPN است؛ تلگرام و اپ‌های دیگر باید از IP وای‌فای این آیفون استفاده کنند.",
        .proxyOnlySocksSelfTestTitle: "آزمایش دسترسی SOCKS5",
        .proxyOnlySocksSelfTestButton: "آزمایش SOCKS5 از همین اپ",
        .proxyOnlySocksSelfTestRunning: "در حال آزمایش…",
        .proxyOnlyTelegramHint: "در تلگرام → Settings → Data and Storage → Proxy: SOCKS5 را روی IP وای‌فای و پورت ۱۰۸۸ بگذارید (نه 127.0.0.1).",
        .proxyOnlyNoWifiSameDevice: "برای استفاده از Proxy Only در اپ‌های همین آیفون به Wi-Fi وصل شوید. فقط با اینترنت سیم‌کارت ممکن است به پروکسی افزونه نرسد.",
        .proxyOnlyPublicIPUnavailable: "IP پروکسی در دسترس نیست",
        .proxyOnlySocksSelfTestWifiOK: "SOCKS5 از طریق IP وای‌فای در دسترس است",
        .proxyOnlySocksSelfTestWifiFailed: "SOCKS5 از طریق IP وای‌فای در دسترس نیست",
        .proxyOnlySocksSelfTestNoWifi: "IP وای‌فای موجود نیست — ابتدا به Wi-Fi وصل شوید.",
        .proxyOnlyRequiresWifiTitle: "Wi-Fi لازم است",
        .proxyOnlyRequiresWifiMessage: "حالت فقط پروکسی به Wi-Fi نیاز دارد. پروکسی SOCKS/HTTP روی همین دستگاه با اینترنت سیم‌کارت کار نمی‌کند چون IP وای‌فای در دسترس نیست. به Wi-Fi وصل شوید یا حالت فقط پروکسی را خاموش کنید.",
        .proxyOnlyTurnOffMode: "خاموش کردن حالت فقط پروکسی",
        .proxyOnlyNotAvailableOnCellular: "روی اینترنت سیم‌کارت در دسترس نیست. برای Proxy Only به Wi-Fi وصل شوید.",
        .bypassRowTitle: "عبور مستقیم IPهای ایران",
        .bypassRowSubtitle: "ترافیک مقصدهای ایرانی مستقیم و خارج از تونل VPN ارسال می‌شود.",
        .bypassNavTitle: "عبور مستقیم IPهای ایران",
        .bypassEnableTitle: "عبور مستقیم IPهای ایران",
        .bypassEnableDescription: "وقتی روشن باشد، محدوده‌های IP ایران مستقیم از شبکهٔ عادی شما عبور می‌کنند و بقیهٔ ترافیک در VPN باقی می‌ماند. در اتصال بعدی اعمال می‌شود.",
        .bypassStatusSection: "وضعیت",
        .bypassListCount: "محدوده‌های IP ایران",
        .bypassListUpdated: "به‌روزرسانی فهرست",
        .bypassRoutesApplied: "مسیرهای اعمال‌شده",
        .bypassNever: "هیچ‌وقت",
        .bypassUpdateListNow: "به‌روزرسانی فهرست",
        .bypassUpdating: "در حال به‌روزرسانی…",
        .bypassListUpdatedToast: "فهرست IP ایران به‌روزرسانی شد.",
        .bypassListFailedToast: "به‌روزرسانی فهرست ناموفق بود. در صورت وجود از نسخهٔ ذخیره‌شده استفاده می‌شود.",
        .bypassCustomSection: "IPها / محدوده‌های سفارشی برای عبور",
        .bypassCustomPlaceholder: "۱.۲.۳.۴ یا 1.2.3.0/24 (هر مورد در یک خط)",
        .bypassCustomHint: "IP منفرد یا محدودهٔ CIDR را برای عبور از VPN اضافه کنید. هر مورد در یک خط.",
        .bypassDomainSection: "دامنه‌ها برای عبور (آزمایشی)",
        .bypassDomainPlaceholder: "example.ir (هر مورد در یک خط)",
        .bypassDomainHint: "دامنه‌ها به آدرس IP تبدیل و به‌عنوان مسیر عبور اضافه می‌شوند.",
        .bypassResolveNow: "تبدیل دامنه‌ها به IP",
        .bypassResolving: "در حال تبدیل…",
        .bypassDomainWarning: "عبور بر اساس دامنه برای سایت‌های پشت CDN یا با IP متغیر قابل‌اعتماد نیست. IPهای به‌دست‌آمده ذخیره و به‌صورت دوره‌ای به‌روز می‌شوند.",
        .bypassSaveApply: "ذخیره و اعمال",
        .bypassSavedToast: "تنظیمات عبور ذخیره شد.",
        .bypassEffectiveNote: "به‌صورت پیش‌فرض، عبور در لایهٔ IP کار می‌کند و رفتار عادی VPN حفظ می‌شود. برای پوشش اپ‌هایی که از پروکسی HTTP سیستم استفاده می‌کنند، از «حالت عبور IP سخت‌گیرانه» بالا استفاده کنید (آزمایشی).",
        .bypassReconnectNote: "تغییرات در اتصال بعدی اعمال می‌شوند. برای اعمال فوری دوباره وصل شوید.",
        .bypassNoListWarning: "فهرست عبور IPهای ایران در دسترس نیست. VPN به‌صورت عادی ادامه می‌یابد.",
        .bypassListSourceBundled: "استفاده از فهرست داخلی (هنوز به‌روزرسانی دانلود نشده).",
        .bypassBestEffortWarning: "برخی اپ‌ها که از پروکسی HTTP سیستم استفاده می‌کنند ممکن است عبور IP را رعایت نکنند. اپ‌هایی که از مسیر tun2socks عبور می‌کنند همچنان می‌توانند از عبور استفاده کنند.",
        .bypassStrictSection: "پیشرفته",
        .bypassStrictToggle: "حالت عبور IP سخت‌گیرانه (آزمایشی)",
        .bypassStrictDescription: "پروکسی HTTP سیستمی داخل تونل را غیرفعال می‌کند تا مسیرهای عبور IP برای همهٔ اپ‌ها از جمله HTTPS اعمال شوند. این کار ممکن است دسترسی عمومی به اینترنت و بررسی IP عمومی را در برخی شرایط مختل کند. اگر مطمئن نیستید روشن نکنید.",
        .messagingCompatRowTitle: "سازگاری پیام‌رسان‌ها",
        .messagingCompatRowSubtitle: "رفع مشکل تلگرام و واتساپ (MTU، DNS، مسیریابی)",
        .messagingCompatNavTitle: "پیام‌رسان‌ها",
        .messagingCompatToggle: "حالت سازگاری",
        .messagingCompatDescription: "وقتی سایت‌ها وصل می‌شوند ولی تلگرام/واتساپ نه کمک می‌کند. MTU را کم می‌کند، ترافیک پیام‌رسان را در تونل نگه می‌دارد، در صورت خاموش بودن DNS امن را فعال می‌کند و CDN/Direct را دوباره امتحان می‌کند.",
        .messagingCompatMtuSection: "MTU تونل",
        .messagingCompatMtu: "MTU",
        .messagingCompatMtuHint: "اگر واتساپ (پورت ۵۲۲۲) قطع است ۱۲۰۰ یا ۱۲۴۰ را امتحان کنید؛ پیش‌فرض ۱۲۸۰ است.",
        .messagingCompatFeaturesSection: "وقتی روشن است",
        .messagingCompatFeatureBypass: "مسیر عبور IP تلگرام/واتساپ را مسدود می‌کند",
        .messagingCompatFeatureDns: "اگر DNS امن خاموش است Cloudflare DoH استفاده می‌شود",
        .messagingCompatFeatureFallback: "هنگام اتصال CDN، Auto+Beast و Direct را امتحان می‌کند",
        .messagingCompatFeatureUdpNote: "UDP تماس صوتی/تصویری رله نمی‌شود (tun2socks فقط TCP). تماس ممکن است هنوز قطع شود.",
        .messagingCompatReconnectNote: "پس از تغییر، VPN را دوباره وصل کنید.",
        .secureDnsRowTitle: "DNS امن",
        .secureDnsRowSubtitle: "رزولور اختیاری DoH/DoT",
        .secureDnsNavTitle: "DNS امن",
        .secureDnsModeSection: "حالت",
        .secureDnsModeOff: "خاموش",
        .secureDnsModeDoh: "DoH",
        .secureDnsModeDot: "DoT",
        .secureDnsModeOffDetail: "همان رفتار فعلی DNS در VPN",
        .secureDnsModeDohDetail: "DNS رمزنگاری‌شده روی HTTPS از مسیر تونل",
        .secureDnsModeDotDetail: "DNS رمزنگاری‌شده روی TLS از مسیر تونل",
        .secureDnsActiveSelection: "انتخاب‌شده",
        .secureDnsProviderSection: "ارائه‌دهنده",
        .secureDnsProviderCloudflare: "Cloudflare",
        .secureDnsProviderGoogle: "Google",
        .secureDnsProviderQuad9: "Quad9",
        .secureDnsProviderAdguard: "AdGuard",
        .secureDnsProviderCustom: "سفارشی",
        .secureDnsCustomDoHURL: "آدرس DoH سفارشی",
        .secureDnsCustomDoTHost: "میزبان DoT سفارشی",
        .secureDnsBlockCleartext: "مسدود کردن DNS شفاف",
        .secureDnsBlockCleartextHint: "اگر DNS امن ناموفق باشد، به DNS قدیمی برنگرد. تا رفع مشکل رزولور، پرس‌وجوهای DNS ممکن است شکست بخورند.",
        .secureDnsTestButton: "آزمایش DNS",
        .secureDnsTestRunning: "در حال آزمایش DNS…",
        .secureDnsTestOk: "آزمایش DNS امن موفق بود",
        .secureDnsTestFailed: "آزمایش DNS امن ناموفق بود",
        .secureDnsTestConnectFirst: "برای آزمایش DNS امن از داخل تونل، ابتدا VPN را وصل کنید.",
        .secureDnsWarningSection: "هشدار",
        .secureDnsDefaultOffNote: "DNS امن به‌صورت پیش‌فرض خاموش است. تا DoH یا DoT را روشن نکنید، رفتار فعلی DNS تغییر نمی‌کند.",
        .secureDnsReconnectNote: "برای اعمال تغییرات DNS امن دوباره وصل شوید.",
        .secureDnsProxyOnlyNote: "DNS امن فقط در حالت VPN کامل اعمال می‌شود. حالت فقط پروکسی تغییر نمی‌کند.",
        .secureDnsBlockedWarning: "DNS امن ناموفق بود و DNS شفاف مسدود است. تنظیمات رزولور را بررسی کنید یا «مسدود کردن DNS شفاف» را خاموش کنید.",
        .secureDnsTestHint: "آزمایش DNS داخل اپ، example.com را از مسیر تونل با ارائه‌دهندهٔ DoH یا DoT انتخاب‌شده resolve می‌کند. در لاگ افزونه به دنبال SECURE_DNS_TEST_OK و SECURE_DNS_DOH_QUERY_OK / SECURE_DNS_DOT_QUERY_OK باشید."
    ]
}
