import Foundation

enum AppLocalizationUI {
    static func register() {
        AppLanguageController.registerExtraTranslations(en: en, fa: fa)
    }

    private static let en: [AppLanguageController.L10nKey: String] = [
        .supportButton: "Support",
        .splashTagline: "Privacy-focused tunnel for a more open internet",
        .diagnosticsSection: "Connection diagnostics",
        .vpnPing: "Ping",
        .copy: "Copy",
        .copiedToClipboard: "Copied to clipboard",
        .testPass: "PASS",
        .testFail: "FAIL",
        .configSetupBanner: "Bundled Psiphon config is missing or invalid. Use Settings → Advanced → Retry bundled install.",
        .onboardingNavTitle: "Welcome",
        .onboardingWelcomeTitle: "Welcome to AzadiTunnel",
        .onboardingWelcomeBody: "AzadiTunnel routes your device traffic through an encrypted Psiphon tunnel so apps can reach the open internet more reliably.",
        .onboardingPrivacyTitle: "Privacy first",
        .onboardingPrivacyBody: "Diagnostics stay on your device. Export debug reports only when you choose. We do not sell your traffic data.",
        .onboardingTransportTitle: "Transport modes",
        .onboardingTransportBody: "Choose Auto, Direct, CDN fronting, or Conduit in Settings. Beast mode speeds up tunnel establishment when enabled.",
        .onboardingFallbackTitle: "Smart fallback",
        .onboardingFallbackBody: "If CDN fronting fails, the app can try Auto+Beast and then Direct automatically, with clear logs for each step.",
        .onboardingSupportTitle: "Support development",
        .onboardingSupportBody: "VPN features stay free. Optional tips and subscriptions help improve the app—open Support from the home screen.",
        .onboardingContinue: "Continue",
        .onboardingGetStarted: "Get started",
        .onboardingSkip: "Skip",
        .protocolAuto: "Auto",
        .protocolDirect: "Direct",
        .protocolCDN: "CDN fronting",
        .protocolConduit: "Conduit",
        .conduitModeAuto: "Auto (community then public)",
        .conduitModeCommunity: "Community",
        .conduitModePublic: "Public",
        .settingsConnection: "Connection",
        .settingsConfigSource: "Config source",
        .settingsBundled: "Bundled",
        .settingsCustom: "Custom",
        .settingsServerEntries: "Embedded server entries",
        .settingsRegion: "Region",
        .settingsEgressRegion: "Egress region",
        .settingsRegionHint: "Region applies on the next connect.",
        .settingsTransport: "Transport",
        .settingsProtocol: "Protocol",
        .settingsBeastMode: "Beast mode",
        .settingsConduitMode: "Conduit mode",
        .settingsBlockCensored: "Block censored-country relays",
        .settingsConduitTimeout: "Auto fallback timeout",
        .settingsCDNFronting: "CDN fronting",
        .settingsCDNExpert: "Expert overrides for CDN edge IPs, SNI, and scan.",
        .settingsCDNBuiltinScan: "Built-in CDN scan",
        .settingsCDNEdgeIPs: "CDN edge IPs",
        .settingsCDNSNI: "CDN SNI hostnames",
        .settingsCDNEdgesSummary: "Built-in edges",
        .settingsProxy: "Upstream proxy",
        .settingsProxyEnable: "Enable upstream proxy",
        .settingsProxyHost: "Host",
        .settingsProxyPort: "Port",
        .settingsProxySystem: "Use system proxy",
        .settingsBehavior: "Behavior",
        .settingsSmartFallback: "Smart fallback (CDN → Auto+Beast → Direct)",
        .settingsAutoReconnect: "Auto-reconnect",
        .settingsConnectOnLaunch: "Connect on launch",
        .settingsVPNOnDemand: "VPN On Demand",
        .settingsVPNOnDemandMode: "Connect when",
        .settingsVPNOnDemandHelp: "iOS connects the tunnel automatically when the rule matches. Install the VPN profile once by tapping Connect on Home.",
        .onDemandAlways: "Any network",
        .onDemandWiFi: "Wi‑Fi only",
        .onDemandCellular: "Cellular only",
        .settingsAdvanced: "Advanced / Developer",
        .settingsAdvancedHint: "Tap Connect on Home to start. Import is optional.",
        .settingsRetryBundled: "Retry bundled install",
        .settingsRetryBundledFailed: "Bundled install failed — see Logs.",
        .settingsBundledInstallSuccess: "Bundled config installed successfully.",
        .settingsConfigImportSuccess: "Custom config imported successfully.",
        .settingsConfigImportFailed: "Config import failed.",
        .settingsDebugReportReady: "Debug report ready — use the share sheet to save or copy.",
        .settingsImportConfig: "Import custom config (JSON)",
        .settingsExportDebug: "Export Debug Report",
        .settingsLegal: "Legal",
        .settingsDisclaimer: "Disclaimer",
        .settingsGPL: "GPL-3.0 License",
        .settingsNotices: "Open source notices",
        .settingsPrivacy: "Privacy",
        .settingsAbout: "About AzadiTunnel",
        .settingsSupport: "Support AzadiTunnel",
        .settingsLogs: "Logs",
        .helpBeastAuto: "Beast + Auto: tries all protocols. Turn off Beast or pick Direct/CDN/Conduit to limit protocols.",
        .helpAuto: "Auto: Psiphon default protocol selection.",
        .helpConduitBlocked: "Conduit requires distributor keys in psiphon-config.local.json (see docs).",
        .helpConduit: "Conduit uses in-proxy WebRTC relays and community pairing. Reconnect after changes.",
        .helpCDN: "CDN uses FRONTED-MEEK-CDN protocols with built-in edge scan and dial overrides.",
        .helpDirect: "Direct uses the direct protocol set only.",
        .errorNoConfig: "No Psiphon config",
        .errorNoConfigSub: "Install bundled resources before connecting.",
        .errorConduitBlocked: "Conduit unavailable",
        .errorConduitBlockedSub: "Add distributor keys to psiphon-config.local.json. Auto and Beast still work.",
        .errorVPNPermission: "VPN permission",
        .errorVPNPermissionSub: "Allow VPN configuration in iOS Settings.",
        .errorOtherVpnBlocking: "Another VPN is active",
        .errorOtherVpnBlockingSub: "iOS allows only one VPN at a time. Open Settings → VPN, turn off the other VPN, then tap Connect here.",
        .openIOSSettings: "Open iOS Settings",
        .errorPsiphonFailed: "Tunnel failed",
        .errorPsiphonFailedSub: "Tunnel could not start. See Logs in Settings.",
        .errorInternetTest: "Internet test failed",
        .errorInternetTestSub: "generate_204 did not return HTTP 204.",
        .changeRegion: "Change region",
        .copyLogLine: "Copy line",
        .copyAllLogs: "Copy all logs",
        .refreshLogs: "Refresh",
        .logsCopiedTitle: "Copied",
        .supportIntro: "Optional tips and subscriptions help development. VPN features stay free.",
        .supportLoading: "Loading products…",
        .supportUnavailable: "Support purchases are not available in this build.",
        .supportRestore: "Restore Purchases",
        .supportStatus: "Status",
        .supportTipsSection: "One-time support",
        .supportSubscriptionsSection: "Subscriptions",
        .supportTipSmall: "Small tip",
        .supportTipMedium: "Medium tip",
        .supportTipLarge: "Large tip",
        .supportMonthly: "Monthly supporter",
        .supportYearly: "Yearly supporter",
        .supportStateNotPurchased: "No support purchase",
        .supportStatePurchased: "Thank you for your support",
        .supportStateSubscribed: "Active supporter subscription",
        .supportStateExpired: "Support subscription expired",
        .supportStateUnknown: "Unknown",
        .supportSubscriptionDisclaimer: "Subscriptions renew automatically unless cancelled at least 24 hours before the end of the current period. VPN features remain free with or without a purchase.",
        .supportManageSubscriptions: "Manage Subscriptions",
        .supportFreeBadge: "Core VPN · Always free",
        .aboutScreenTitle: "About",
        .aboutDeveloperLabel: "Company",
        .aboutDeveloperValue: "Debugsy Inc.",
        .aboutAppVersionLabel: "App Version",
        .aboutCoreVersionLabel: "Core Version",
        .aboutCoreVersionValue: "Psiphon + tun2socks",
        .aboutRateUs: "Rate Us",
        .aboutWebsite: "Psiphon (psiphon.ca)",
        .aboutPsiphonGitHub: "Psiphon on GitHub",
        .aboutCompanyWebsite: "Debugsy Inc.",
        .aboutX: "X",
        .aboutContactUs: "Contact Us",
        .aboutTerms: "Terms & Conditions",
        .aboutCopyright: "© %d Debugsy Inc. All rights reserved.",
        .aboutResponsibleUse: "Users are responsible for using the app lawfully and responsibly.",
        .aboutOpenSourceAck: "Open-source components are acknowledged in Legal & Open Source.",
        .legalOpenSourceTitle: "Legal & Open Source",
        .privacyNoticeTitle: "Privacy Notice",
        .beforeYouConnectTitle: "Before You Connect",
        .disclaimerIntro: "AzadiTunnel is a privacy-focused tunneling app designed to help users access a more open and reliable internet. Network behavior may vary depending on your location, provider, and local regulations.",
        .disclaimerResponsibleUseTitle: "Responsible use",
        .disclaimerResponsibleUse: "Use AzadiTunnel responsibly and only in ways that comply with applicable laws and the terms of services you use.",
        .disclaimerNoGuaranteeTitle: "No guarantee",
        .disclaimerNoGuarantee: "AzadiTunnel cannot guarantee uninterrupted access, complete anonymity, or protection against every type of network monitoring.",
        .disclaimerPrivacyDiagnosticsTitle: "Privacy and diagnostics",
        .disclaimerPrivacyDiagnostics: "The app may show connection logs, IP/DNS leak test results, quality reports, and diagnostic information to help you understand your connection. Do not share debug reports publicly unless you review them first.",
        .disclaimerNoIllegalContentTitle: "No built-in illegal content",
        .disclaimerNoIllegalContent: "AzadiTunnel does not provide illegal content and does not include preset paid servers in this build.",
        .disclaimerThirdPartyNetworksTitle: "Third-party networks",
        .disclaimerThirdPartyNetworks: "Some connection methods may rely on third-party infrastructure or open-source tunneling technologies. Availability and performance can change.",
        .iUnderstandAndAgree: "I Understand and Agree",
        .cancel: "Cancel",
        .viewFullLicenseNotices: "View Full License Notices",
        .legalAppLicenseSection: "App license",
        .legalOpenSourceComponentsSection: "Open-source acknowledgements",
        .legalGplWarningSection: "GPL / copyleft notice",
        .legalGplWarningBody: "Some components may be licensed under GPLv3. If GPLv3 code is included, the complete corresponding source code and license notices must be provided as required by the GPLv3 license.",
        .legalLicenseUnavailable: "License information is not available in this build.",
        .legalLicenseLabel: "License",
        .privacyNoticeBody: "AzadiTunnel is designed to minimize data collection. The app stores your tunnel settings locally on your device. Debug logs may include connection status, selected transport, protocol names, public IP test results, DNS test results, and device/app version information. Debug reports remove secrets before export.",
        .privacyNoticeNoSecrets: "We do not intentionally log private keys, server entry signature keys, obfuscation keys, user tokens, or full raw configs containing secrets.",
        .privacyNoticeReviewExport: "If you export a debug report, review it before sharing.",
        .privacyNoticeStoreKit: "Support purchases, if available, are handled by Apple through StoreKit."
    ]

    private static let fa: [AppLanguageController.L10nKey: String] = [
        .supportButton: "حمایت",
        .splashTagline: "تونل متمرکز بر حریم خصوصی برای اینترنت بازتر",
        .diagnosticsSection: "تشخیص اتصال",
        .vpnPing: "پینگ",
        .copy: "کپی",
        .copiedToClipboard: "در کلیپ‌بورد کپی شد",
        .testPass: "موفق",
        .testFail: "ناموفق",
        .configSetupBanner: "پیکربندی Psiphon بستهٔ داخلی موجود یا نامعتبر است. تنظیمات → پیشرفته → نصب مجدد بسته.",
        .onboardingNavTitle: "خوش آمدید",
        .onboardingWelcomeTitle: "به AzadiTunnel خوش آمدید",
        .onboardingWelcomeBody: "AzadiTunnel ترافیک دستگاه را از تونل رمزگذاری‌شده Psiphon عبور می‌دهد تا اپ‌ها به اینترنت بازتر دسترسی داشته باشند.",
        .onboardingPrivacyTitle: "حریم خصوصی",
        .onboardingPrivacyBody: "تشخیص‌ها روی دستگاه می‌ماند. گزارش اشکال‌زدایی فقط با انتخاب شما صادر می‌شود.",
        .onboardingTransportTitle: "حالت‌های حمل‌ونقل",
        .onboardingTransportBody: "در تنظیمات Auto، Direct، CDN fronting یا Conduit را انتخاب کنید. Beast برقراری تونل را تسریع می‌کند.",
        .onboardingFallbackTitle: "جایگزین هوشمند",
        .onboardingFallbackBody: "اگر CDN fronting ناموفق باشد، اپ می‌تواند Auto+Beast و سپس Direct را امتحان کند.",
        .onboardingSupportTitle: "حمایت از توسعه",
        .onboardingSupportBody: "قابلیت VPN رایگان می‌ماند. انعام و اشتراک اختیاری از صفحهٔ اصلی در دسترس است.",
        .onboardingContinue: "ادامه",
        .onboardingGetStarted: "شروع",
        .onboardingSkip: "رد کردن",
        .protocolAuto: "خودکار",
        .protocolDirect: "مستقیم",
        .protocolCDN: "CDN fronting",
        .protocolConduit: "کندویت",
        .conduitModeAuto: "خودکار (جامعه سپس عمومی)",
        .conduitModeCommunity: "جامعه",
        .conduitModePublic: "عمومی",
        .settingsConnection: "اتصال",
        .settingsConfigSource: "منبع پیکربندی",
        .settingsBundled: "بستهٔ داخلی",
        .settingsCustom: "سفارشی",
        .settingsServerEntries: "ورودی‌های سرور",
        .settingsRegion: "منطقه",
        .settingsEgressRegion: "منطقه خروجی",
        .settingsRegionHint: "منطقه در اتصال بعدی اعمال می‌شود.",
        .settingsTransport: "حمل‌ونقل",
        .settingsProtocol: "پروتکل",
        .settingsBeastMode: "حالت Beast",
        .settingsConduitMode: "حالت Conduit",
        .settingsBlockCensored: "مسدودسازی رله کشورهای سانسورشده",
        .settingsConduitTimeout: "مهلت جایگزین خودکار",
        .settingsCDNFronting: "CDN fronting",
        .settingsCDNExpert: "تنظیمات پیشرفته IP لبه، SNI و اسکن CDN.",
        .settingsCDNBuiltinScan: "اسکن CDN داخلی",
        .settingsCDNEdgeIPs: "IP لبه CDN",
        .settingsCDNSNI: "نام‌های SNI",
        .settingsCDNEdgesSummary: "لبه‌های داخلی",
        .settingsProxy: "پروکسی بالادست",
        .settingsProxyEnable: "فعال‌سازی پروکسی",
        .settingsProxyHost: "میزبان",
        .settingsProxyPort: "پورت",
        .settingsProxySystem: "پروکسی سیستم",
        .settingsBehavior: "رفتار",
        .settingsSmartFallback: "جایگزین هوشمند (CDN → Auto+Beast → Direct)",
        .settingsAutoReconnect: "اتصال مجدد خودکار",
        .settingsConnectOnLaunch: "اتصال هنگام اجرا",
        .settingsVPNOnDemand: "VPN On Demand",
        .settingsVPNOnDemandMode: "اتصال هنگام",
        .settingsVPNOnDemandHelp: "iOS با تطبیق قانون، تونل را خودکار وصل می‌کند. یک‌بار در صفحهٔ اصلی Connect را بزنید تا پروفایل VPN ساخته شود.",
        .onDemandAlways: "هر شبکه",
        .onDemandWiFi: "فقط Wi‑Fi",
        .onDemandCellular: "فقط سلولی",
        .settingsAdvanced: "پیشرفته / توسعه",
        .settingsAdvancedHint: "در صفحهٔ اصلی Connect را بزنید. وارد کردن اختیاری است.",
        .settingsRetryBundled: "نصب مجدد بستهٔ داخلی",
        .settingsRetryBundledFailed: "نصب بسته ناموفق بود — گزارش‌ها را ببینید.",
        .settingsBundledInstallSuccess: "پیکربندی بستهٔ داخلی با موفقیت نصب شد.",
        .settingsConfigImportSuccess: "پیکربندی سفارشی با موفقیت وارد شد.",
        .settingsConfigImportFailed: "وارد کردن پیکربندی ناموفق بود.",
        .settingsDebugReportReady: "گزارش اشکال‌زدایی آماده است — از اشتراک‌گذاری ذخیره یا کپی کنید.",
        .settingsImportConfig: "وارد کردن پیکربندی (JSON)",
        .settingsExportDebug: "صادرات گزارش اشکال‌زدایی",
        .settingsLegal: "حقوقی",
        .settingsDisclaimer: "سلب مسئولیت",
        .settingsGPL: "مجوز GPL-3.0",
        .settingsNotices: "اعلامیه‌های متن‌باز",
        .settingsPrivacy: "حریم خصوصی",
        .settingsAbout: "درباره AzadiTunnel",
        .settingsSupport: "حمایت از AzadiTunnel",
        .settingsLogs: "گزارش‌ها",
        .helpBeastAuto: "Beast + Auto: همه پروتکل‌ها. Beast را خاموش کنید یا Direct/CDN/Conduit انتخاب کنید.",
        .helpAuto: "Auto: انتخاب پیش‌فرض Psiphon.",
        .helpConduitBlocked: "Conduit به کلیدهای توزیع‌کننده در psiphon-config.local.json نیاز دارد.",
        .helpConduit: "Conduit از رله WebRTC و جفت‌سازی جامعه استفاده می‌کند.",
        .helpCDN: "CDN از پروتکل‌های FRONTED-MEEK-CDN با اسکن لبه استفاده می‌کند.",
        .helpDirect: "Direct فقط مجموعه پروتکل مستقیم.",
        .errorNoConfig: "بدون پیکربندی Psiphon",
        .errorNoConfigSub: "قبل از اتصال منابع بسته را نصب کنید.",
        .errorConduitBlocked: "Conduit در دسترس نیست",
        .errorConduitBlockedSub: "کلیدهای توزیع‌کننده را اضافه کنید. Auto و Beast کار می‌کنند.",
        .errorVPNPermission: "مجوز VPN",
        .errorVPNPermissionSub: "در تنظیمات iOS مجوز VPN را بدهید.",
        .errorOtherVpnBlocking: "VPN دیگری فعال است",
        .errorOtherVpnBlockingSub: "iOS فقط یک VPN هم‌زمان اجازه می‌دهد. تنظیمات → VPN را باز کنید، VPN دیگر را خاموش کنید، بعد اینجا Connect بزنید.",
        .openIOSSettings: "باز کردن تنظیمات iOS",
        .errorPsiphonFailed: "خطای تونل",
        .errorPsiphonFailedSub: "تونل شروع نشد. گزارش‌ها را در تنظیمات ببینید.",
        .errorInternetTest: "آزمون اینترنت ناموفق",
        .errorInternetTestSub: "generate_204 کد 204 برنگرداند.",
        .changeRegion: "تغییر منطقه",
        .copyLogLine: "کپی خط",
        .copyAllLogs: "کپی همه",
        .refreshLogs: "بازخوانی",
        .logsCopiedTitle: "کپی شد",
        .supportIntro: "انعام و اشتراک اختیاری به توسعه کمک می‌کند. VPN رایگان می‌ماند.",
        .supportLoading: "در حال بارگذاری محصولات…",
        .supportUnavailable: "خرید پشتیبانی در این نسخه در دسترس نیست.",
        .supportRestore: "بازیابی خریدها",
        .supportStatus: "وضعیت",
        .supportTipsSection: "پشتیبانی یک‌بار",
        .supportSubscriptionsSection: "اشتراک",
        .supportTipSmall: "انعام کوچک",
        .supportTipMedium: "انعام متوسط",
        .supportTipLarge: "انعام بزرگ",
        .supportMonthly: "حامی ماهانه",
        .supportYearly: "حامی سالانه",
        .supportStateNotPurchased: "بدون خرید پشتیبانی",
        .supportStatePurchased: "از حمایت شما سپاسگزاریم",
        .supportStateSubscribed: "اشتراک حمایت فعال",
        .supportStateExpired: "اشتراک حمایت منقضی شده",
        .supportStateUnknown: "نامشخص",
        .supportSubscriptionDisclaimer: "اشتراک‌ها به‌صورت خودکار تمدید می‌شوند مگر حداقل ۲۴ ساعت قبل از پایان دوره لغو شوند. VPN با یا بدون خرید رایگان می‌ماند.",
        .supportManageSubscriptions: "مدیریت اشتراک‌ها",
        .supportFreeBadge: "VPN اصلی · همیشه رایگان",
        .aboutScreenTitle: "درباره",
        .aboutDeveloperLabel: "شرکت",
        .aboutDeveloperValue: "Debugsy Inc.",
        .aboutAppVersionLabel: "نسخهٔ اپ",
        .aboutCoreVersionLabel: "نسخهٔ هسته",
        .aboutCoreVersionValue: "Psiphon + tun2socks",
        .aboutRateUs: "امتیازدهی",
        .aboutWebsite: "Psiphon (psiphon.ca)",
        .aboutPsiphonGitHub: "Psiphon در GitHub",
        .aboutCompanyWebsite: "Debugsy Inc.",
        .aboutX: "X",
        .aboutContactUs: "تماس با ما",
        .aboutTerms: "شرایط و ضوابط",
        .aboutCopyright: "© %d Debugsy Inc. تمامی حقوق محفوظ است.",
        .aboutResponsibleUse: "کاربران مسئول استفادهٔ قانونی و مسئولانه از اپ هستند.",
        .aboutOpenSourceAck: "اجزای متن‌باز در «حقوقی و متن‌باز» ذکر شده‌اند.",
        .legalOpenSourceTitle: "حقوقی و متن‌باز",
        .privacyNoticeTitle: "اطلاعیهٔ حریم خصوصی",
        .beforeYouConnectTitle: "قبل از اتصال",
        .disclaimerIntro: "AzadiTunnel یک اپ تونل متمرکز بر حریم خصوصی است که برای دسترسی بازتر و پایدارتر به اینترنت طراحی شده است. رفتار شبکه بسته به موقعیت، ارائه‌دهنده و مقررات محلی متفاوت است.",
        .disclaimerResponsibleUseTitle: "استفادهٔ مسئولانه",
        .disclaimerResponsibleUse: "AzadiTunnel را مسئولانه و فقط مطابق قوانین و شرایط سرویس‌هایی که استفاده می‌کنید به کار ببرید.",
        .disclaimerNoGuaranteeTitle: "بدون تضمین",
        .disclaimerNoGuarantee: "AzadiTunnel نمی‌تواند دسترسی بدون وقفه، ناشناس بودن کامل یا محافظت در برابر همهٔ انواع پایش شبکه را تضمین کند.",
        .disclaimerPrivacyDiagnosticsTitle: "حریم خصوصی و تشخیص",
        .disclaimerPrivacyDiagnostics: "اپ ممکن است گزارش اتصال، نتایج آزمون نشت IP/DNS، گزارش کیفیت و اطلاعات تشخیصی نشان دهد. گزارش اشکال‌زدایی را بدون بازبینی عمومی نکنید.",
        .disclaimerNoIllegalContentTitle: "بدون محتوای غیرقانونی داخلی",
        .disclaimerNoIllegalContent: "AzadiTunnel محتوای غیرقانونی ارائه نمی‌دهد و سرور پولی از پیش تنظیم‌شده در این نسخه ندارد.",
        .disclaimerThirdPartyNetworksTitle: "شبکه‌های شخص ثالث",
        .disclaimerThirdPartyNetworks: "برخی روش‌های اتصال ممکن است به زیرساخت شخص ثالث یا فناوری تونل متن‌باز وابسته باشند. دسترس‌پذیری و عملکرد می‌تواند تغییر کند.",
        .iUnderstandAndAgree: "می‌فهمم و موافقم",
        .cancel: "لغو",
        .viewFullLicenseNotices: "مشاهدهٔ اطلاعیه‌های کامل مجوز",
        .legalAppLicenseSection: "مجوز اپ",
        .legalOpenSourceComponentsSection: "سپاس متن‌باز",
        .legalGplWarningSection: "اطلاعیهٔ GPL / copyleft",
        .legalGplWarningBody: "برخی اجزا ممکن است تحت GPLv3 باشند. در صورت شامل بودن کد GPLv3، ارائهٔ سورس کامل و اطلاعیه‌های مجوز طبق GPLv3 لازم است.",
        .legalLicenseUnavailable: "اطلاعات مجوز در این نسخه در دسترس نیست.",
        .legalLicenseLabel: "مجوز",
        .privacyNoticeBody: "AzadiTunnel برای کمینه کردن جمع‌آوری داده طراحی شده است. تنظیمات تونل روی دستگاه شما ذخیره می‌شود. گزارش اشکال‌زدایی ممکن است وضعیت اتصال، حمل‌ونقل، پروتکل، IP عمومی، DNS و نسخهٔ اپ/دستگاه را شامل شود. گزارش‌ها قبل از صادرات پاک‌سازی می‌شوند.",
        .privacyNoticeNoSecrets: "عمداً کلیدهای خصوصی، کلیدهای امضای server entry، کلید obfuscation، توکن کاربر یا پیکربندی خام کامل حاوی راز را ثبت نمی‌کنیم.",
        .privacyNoticeReviewExport: "قبل از اشتراک‌گذاری گزارش اشکال‌زدایی، آن را بازبینی کنید.",
        .privacyNoticeStoreKit: "خریدهای پشتیبانی، در صورت وجود، از طریق StoreKit اپل انجام می‌شود."
    ]
}
